-- LJ-1.185, probe B: the base spelling.
--
-- Generated by `agents/tasks/LJ-1-185/gen_probe.py`. Do not edit by hand.
-- shape=base defs=12 ladder=13 width=24 apps=0
--
-- Read it TWICE, once with `--profile=definitions` and once with
-- `--profile=internal`. Agda 2.8.0 refuses both in one run.

{-# OPTIONS --cubical --safe --guardedness #-}

module LJ-1-185.ProbeLJ1185B where

open import Cubical.Foundations.Prelude

-- A private unary carrier. It names nothing in either tower (DD4).

data N : Type where
  z : N
  s : N → N

infixl 6 _⊕_

_⊕_ : N → N → N
z     ⊕ m = m
(s n) ⊕ m = s (n ⊕ m)

-- A doubling ladder, so one name stands for a deep term.

d0 : N
d0 = s z

d1 : N
d1 = d0 ⊕ d0

d2 : N
d2 = d1 ⊕ d1

d3 : N
d3 = d2 ⊕ d2

d4 : N
d4 = d3 ⊕ d3

d5 : N
d5 = d4 ⊕ d4

d6 : N
d6 = d5 ⊕ d5

d7 : N
d7 = d6 ⊕ d6

d8 : N
d8 = d7 ⊕ d7

d9 : N
d9 = d8 ⊕ d8

d10 : N
d10 = d9 ⊕ d9

d11 : N
d11 = d10 ⊕ d10

d12 : N
d12 = d11 ⊕ d11

d13 : N
d13 = d12 ⊕ d12

-- The definitions, at file level.

f0 : d13 ⊕ z ≡ d13
f0 = refl

g0 : (d13 ⊕ z) ⊕ z ≡ d13 ⊕ z
g0 = cong (_⊕ z) f0

f1 : d12 ⊕ z ≡ d12
f1 = refl

g1 : (d12 ⊕ z) ⊕ z ≡ d12 ⊕ z
g1 = cong (_⊕ z) f1

f2 : d11 ⊕ z ≡ d11
f2 = refl

g2 : (d11 ⊕ z) ⊕ z ≡ d11 ⊕ z
g2 = cong (_⊕ z) f2

f3 : d13 ⊕ z ≡ d13
f3 = refl

g3 : (d13 ⊕ z) ⊕ z ≡ d13 ⊕ z
g3 = cong (_⊕ z) f3

f4 : d12 ⊕ z ≡ d12
f4 = refl

g4 : (d12 ⊕ z) ⊕ z ≡ d12 ⊕ z
g4 = cong (_⊕ z) f4

f5 : d11 ⊕ z ≡ d11
f5 = refl

g5 : (d11 ⊕ z) ⊕ z ≡ d11 ⊕ z
g5 = cong (_⊕ z) f5

f6 : d13 ⊕ z ≡ d13
f6 = refl

g6 : (d13 ⊕ z) ⊕ z ≡ d13 ⊕ z
g6 = cong (_⊕ z) f6

f7 : d12 ⊕ z ≡ d12
f7 = refl

g7 : (d12 ⊕ z) ⊕ z ≡ d12 ⊕ z
g7 = cong (_⊕ z) f7

f8 : d11 ⊕ z ≡ d11
f8 = refl

g8 : (d11 ⊕ z) ⊕ z ≡ d11 ⊕ z
g8 = cong (_⊕ z) f8

f9 : d13 ⊕ z ≡ d13
f9 = refl

g9 : (d13 ⊕ z) ⊕ z ≡ d13 ⊕ z
g9 = cong (_⊕ z) f9

f10 : d12 ⊕ z ≡ d12
f10 = refl

g10 : (d12 ⊕ z) ⊕ z ≡ d12 ⊕ z
g10 = cong (_⊕ z) f10

f11 : d11 ⊕ z ≡ d11
f11 = refl

g11 : (d11 ⊕ z) ⊕ z ≡ d11 ⊕ z
g11 = cong (_⊕ z) f11
