-- LJ-1.185, probe C: the tele spelling.
--
-- Generated by `agents/tasks/LJ-1-185/gen_probe.py`. Do not edit by hand.
-- shape=tele defs=12 ladder=13 width=24 apps=0
--
-- Read it TWICE, once with `--profile=definitions` and once with
-- `--profile=internal`. Agda 2.8.0 refuses both in one run.

{-# OPTIONS --cubical --safe --guardedness #-}

module LJ-1-185.ProbeLJ1185C where

open import Cubical.Foundations.Prelude

-- A private unary carrier. It names nothing in either tower (DD4).

data N : Type where
  z : N
  s : N → N

infixl 6 _⊕_

_⊕_ : N → N → N
z     ⊕ m = m
(s n) ⊕ m = s (n ⊕ m)

-- A doubling ladder, so one name stands for a deep term.

d0 : N
d0 = s z

d1 : N
d1 = d0 ⊕ d0

d2 : N
d2 = d1 ⊕ d1

d3 : N
d3 = d2 ⊕ d2

d4 : N
d4 = d3 ⊕ d3

d5 : N
d5 = d4 ⊕ d4

d6 : N
d6 = d5 ⊕ d5

d7 : N
d7 = d6 ⊕ d6

d8 : N
d8 = d7 ⊕ d7

d9 : N
d9 = d8 ⊕ d8

d10 : N
d10 = d9 ⊕ d9

d11 : N
d11 = d10 ⊕ d10

d12 : N
d12 = d11 ⊕ d11

d13 : N
d13 = d12 ⊕ d12

-- The definitions, under a telescope of 24 hypotheses.

module Body (p0 p1 p2 p3 p4 p5 p6 p7 p8 p9 p10 p11 p12 p13 p14 p15 p16 p17 p18 p19 p20 p21 p22 p23 : N) where

  f0 : (p0 ⊕ p1 ⊕ p2 ⊕ p3 ⊕ p4 ⊕ p5 ⊕ p6 ⊕ p7 ⊕ p8 ⊕ p9 ⊕ p10 ⊕ p11 ⊕ p12 ⊕ p13 ⊕ p14 ⊕ p15 ⊕ p16 ⊕ p17 ⊕ p18 ⊕ p19 ⊕ p20 ⊕ p21 ⊕ p22 ⊕ p23) ⊕ d13 ≡ (p0 ⊕ p1 ⊕ p2 ⊕ p3 ⊕ p4 ⊕ p5 ⊕ p6 ⊕ p7 ⊕ p8 ⊕ p9 ⊕ p10 ⊕ p11 ⊕ p12 ⊕ p13 ⊕ p14 ⊕ p15 ⊕ p16 ⊕ p17 ⊕ p18 ⊕ p19 ⊕ p20 ⊕ p21 ⊕ p22 ⊕ p23) ⊕ d13
  f0 = refl

  g0 : ((p0 ⊕ p1 ⊕ p2 ⊕ p3 ⊕ p4 ⊕ p5 ⊕ p6 ⊕ p7 ⊕ p8 ⊕ p9 ⊕ p10 ⊕ p11 ⊕ p12 ⊕ p13 ⊕ p14 ⊕ p15 ⊕ p16 ⊕ p17 ⊕ p18 ⊕ p19 ⊕ p20 ⊕ p21 ⊕ p22 ⊕ p23) ⊕ d13) ⊕ z ≡ ((p0 ⊕ p1 ⊕ p2 ⊕ p3 ⊕ p4 ⊕ p5 ⊕ p6 ⊕ p7 ⊕ p8 ⊕ p9 ⊕ p10 ⊕ p11 ⊕ p12 ⊕ p13 ⊕ p14 ⊕ p15 ⊕ p16 ⊕ p17 ⊕ p18 ⊕ p19 ⊕ p20 ⊕ p21 ⊕ p22 ⊕ p23) ⊕ d13) ⊕ z
  g0 = cong (_⊕ z) f0

  f1 : (p0 ⊕ p1 ⊕ p2 ⊕ p3 ⊕ p4 ⊕ p5 ⊕ p6 ⊕ p7 ⊕ p8 ⊕ p9 ⊕ p10 ⊕ p11 ⊕ p12 ⊕ p13 ⊕ p14 ⊕ p15 ⊕ p16 ⊕ p17 ⊕ p18 ⊕ p19 ⊕ p20 ⊕ p21 ⊕ p22 ⊕ p23) ⊕ d12 ≡ (p0 ⊕ p1 ⊕ p2 ⊕ p3 ⊕ p4 ⊕ p5 ⊕ p6 ⊕ p7 ⊕ p8 ⊕ p9 ⊕ p10 ⊕ p11 ⊕ p12 ⊕ p13 ⊕ p14 ⊕ p15 ⊕ p16 ⊕ p17 ⊕ p18 ⊕ p19 ⊕ p20 ⊕ p21 ⊕ p22 ⊕ p23) ⊕ d12
  f1 = refl

  g1 : ((p0 ⊕ p1 ⊕ p2 ⊕ p3 ⊕ p4 ⊕ p5 ⊕ p6 ⊕ p7 ⊕ p8 ⊕ p9 ⊕ p10 ⊕ p11 ⊕ p12 ⊕ p13 ⊕ p14 ⊕ p15 ⊕ p16 ⊕ p17 ⊕ p18 ⊕ p19 ⊕ p20 ⊕ p21 ⊕ p22 ⊕ p23) ⊕ d12) ⊕ z ≡ ((p0 ⊕ p1 ⊕ p2 ⊕ p3 ⊕ p4 ⊕ p5 ⊕ p6 ⊕ p7 ⊕ p8 ⊕ p9 ⊕ p10 ⊕ p11 ⊕ p12 ⊕ p13 ⊕ p14 ⊕ p15 ⊕ p16 ⊕ p17 ⊕ p18 ⊕ p19 ⊕ p20 ⊕ p21 ⊕ p22 ⊕ p23) ⊕ d12) ⊕ z
  g1 = cong (_⊕ z) f1

  f2 : (p0 ⊕ p1 ⊕ p2 ⊕ p3 ⊕ p4 ⊕ p5 ⊕ p6 ⊕ p7 ⊕ p8 ⊕ p9 ⊕ p10 ⊕ p11 ⊕ p12 ⊕ p13 ⊕ p14 ⊕ p15 ⊕ p16 ⊕ p17 ⊕ p18 ⊕ p19 ⊕ p20 ⊕ p21 ⊕ p22 ⊕ p23) ⊕ d11 ≡ (p0 ⊕ p1 ⊕ p2 ⊕ p3 ⊕ p4 ⊕ p5 ⊕ p6 ⊕ p7 ⊕ p8 ⊕ p9 ⊕ p10 ⊕ p11 ⊕ p12 ⊕ p13 ⊕ p14 ⊕ p15 ⊕ p16 ⊕ p17 ⊕ p18 ⊕ p19 ⊕ p20 ⊕ p21 ⊕ p22 ⊕ p23) ⊕ d11
  f2 = refl

  g2 : ((p0 ⊕ p1 ⊕ p2 ⊕ p3 ⊕ p4 ⊕ p5 ⊕ p6 ⊕ p7 ⊕ p8 ⊕ p9 ⊕ p10 ⊕ p11 ⊕ p12 ⊕ p13 ⊕ p14 ⊕ p15 ⊕ p16 ⊕ p17 ⊕ p18 ⊕ p19 ⊕ p20 ⊕ p21 ⊕ p22 ⊕ p23) ⊕ d11) ⊕ z ≡ ((p0 ⊕ p1 ⊕ p2 ⊕ p3 ⊕ p4 ⊕ p5 ⊕ p6 ⊕ p7 ⊕ p8 ⊕ p9 ⊕ p10 ⊕ p11 ⊕ p12 ⊕ p13 ⊕ p14 ⊕ p15 ⊕ p16 ⊕ p17 ⊕ p18 ⊕ p19 ⊕ p20 ⊕ p21 ⊕ p22 ⊕ p23) ⊕ d11) ⊕ z
  g2 = cong (_⊕ z) f2

  f3 : (p0 ⊕ p1 ⊕ p2 ⊕ p3 ⊕ p4 ⊕ p5 ⊕ p6 ⊕ p7 ⊕ p8 ⊕ p9 ⊕ p10 ⊕ p11 ⊕ p12 ⊕ p13 ⊕ p14 ⊕ p15 ⊕ p16 ⊕ p17 ⊕ p18 ⊕ p19 ⊕ p20 ⊕ p21 ⊕ p22 ⊕ p23) ⊕ d13 ≡ (p0 ⊕ p1 ⊕ p2 ⊕ p3 ⊕ p4 ⊕ p5 ⊕ p6 ⊕ p7 ⊕ p8 ⊕ p9 ⊕ p10 ⊕ p11 ⊕ p12 ⊕ p13 ⊕ p14 ⊕ p15 ⊕ p16 ⊕ p17 ⊕ p18 ⊕ p19 ⊕ p20 ⊕ p21 ⊕ p22 ⊕ p23) ⊕ d13
  f3 = refl

  g3 : ((p0 ⊕ p1 ⊕ p2 ⊕ p3 ⊕ p4 ⊕ p5 ⊕ p6 ⊕ p7 ⊕ p8 ⊕ p9 ⊕ p10 ⊕ p11 ⊕ p12 ⊕ p13 ⊕ p14 ⊕ p15 ⊕ p16 ⊕ p17 ⊕ p18 ⊕ p19 ⊕ p20 ⊕ p21 ⊕ p22 ⊕ p23) ⊕ d13) ⊕ z ≡ ((p0 ⊕ p1 ⊕ p2 ⊕ p3 ⊕ p4 ⊕ p5 ⊕ p6 ⊕ p7 ⊕ p8 ⊕ p9 ⊕ p10 ⊕ p11 ⊕ p12 ⊕ p13 ⊕ p14 ⊕ p15 ⊕ p16 ⊕ p17 ⊕ p18 ⊕ p19 ⊕ p20 ⊕ p21 ⊕ p22 ⊕ p23) ⊕ d13) ⊕ z
  g3 = cong (_⊕ z) f3

  f4 : (p0 ⊕ p1 ⊕ p2 ⊕ p3 ⊕ p4 ⊕ p5 ⊕ p6 ⊕ p7 ⊕ p8 ⊕ p9 ⊕ p10 ⊕ p11 ⊕ p12 ⊕ p13 ⊕ p14 ⊕ p15 ⊕ p16 ⊕ p17 ⊕ p18 ⊕ p19 ⊕ p20 ⊕ p21 ⊕ p22 ⊕ p23) ⊕ d12 ≡ (p0 ⊕ p1 ⊕ p2 ⊕ p3 ⊕ p4 ⊕ p5 ⊕ p6 ⊕ p7 ⊕ p8 ⊕ p9 ⊕ p10 ⊕ p11 ⊕ p12 ⊕ p13 ⊕ p14 ⊕ p15 ⊕ p16 ⊕ p17 ⊕ p18 ⊕ p19 ⊕ p20 ⊕ p21 ⊕ p22 ⊕ p23) ⊕ d12
  f4 = refl

  g4 : ((p0 ⊕ p1 ⊕ p2 ⊕ p3 ⊕ p4 ⊕ p5 ⊕ p6 ⊕ p7 ⊕ p8 ⊕ p9 ⊕ p10 ⊕ p11 ⊕ p12 ⊕ p13 ⊕ p14 ⊕ p15 ⊕ p16 ⊕ p17 ⊕ p18 ⊕ p19 ⊕ p20 ⊕ p21 ⊕ p22 ⊕ p23) ⊕ d12) ⊕ z ≡ ((p0 ⊕ p1 ⊕ p2 ⊕ p3 ⊕ p4 ⊕ p5 ⊕ p6 ⊕ p7 ⊕ p8 ⊕ p9 ⊕ p10 ⊕ p11 ⊕ p12 ⊕ p13 ⊕ p14 ⊕ p15 ⊕ p16 ⊕ p17 ⊕ p18 ⊕ p19 ⊕ p20 ⊕ p21 ⊕ p22 ⊕ p23) ⊕ d12) ⊕ z
  g4 = cong (_⊕ z) f4

  f5 : (p0 ⊕ p1 ⊕ p2 ⊕ p3 ⊕ p4 ⊕ p5 ⊕ p6 ⊕ p7 ⊕ p8 ⊕ p9 ⊕ p10 ⊕ p11 ⊕ p12 ⊕ p13 ⊕ p14 ⊕ p15 ⊕ p16 ⊕ p17 ⊕ p18 ⊕ p19 ⊕ p20 ⊕ p21 ⊕ p22 ⊕ p23) ⊕ d11 ≡ (p0 ⊕ p1 ⊕ p2 ⊕ p3 ⊕ p4 ⊕ p5 ⊕ p6 ⊕ p7 ⊕ p8 ⊕ p9 ⊕ p10 ⊕ p11 ⊕ p12 ⊕ p13 ⊕ p14 ⊕ p15 ⊕ p16 ⊕ p17 ⊕ p18 ⊕ p19 ⊕ p20 ⊕ p21 ⊕ p22 ⊕ p23) ⊕ d11
  f5 = refl

  g5 : ((p0 ⊕ p1 ⊕ p2 ⊕ p3 ⊕ p4 ⊕ p5 ⊕ p6 ⊕ p7 ⊕ p8 ⊕ p9 ⊕ p10 ⊕ p11 ⊕ p12 ⊕ p13 ⊕ p14 ⊕ p15 ⊕ p16 ⊕ p17 ⊕ p18 ⊕ p19 ⊕ p20 ⊕ p21 ⊕ p22 ⊕ p23) ⊕ d11) ⊕ z ≡ ((p0 ⊕ p1 ⊕ p2 ⊕ p3 ⊕ p4 ⊕ p5 ⊕ p6 ⊕ p7 ⊕ p8 ⊕ p9 ⊕ p10 ⊕ p11 ⊕ p12 ⊕ p13 ⊕ p14 ⊕ p15 ⊕ p16 ⊕ p17 ⊕ p18 ⊕ p19 ⊕ p20 ⊕ p21 ⊕ p22 ⊕ p23) ⊕ d11) ⊕ z
  g5 = cong (_⊕ z) f5

  f6 : (p0 ⊕ p1 ⊕ p2 ⊕ p3 ⊕ p4 ⊕ p5 ⊕ p6 ⊕ p7 ⊕ p8 ⊕ p9 ⊕ p10 ⊕ p11 ⊕ p12 ⊕ p13 ⊕ p14 ⊕ p15 ⊕ p16 ⊕ p17 ⊕ p18 ⊕ p19 ⊕ p20 ⊕ p21 ⊕ p22 ⊕ p23) ⊕ d13 ≡ (p0 ⊕ p1 ⊕ p2 ⊕ p3 ⊕ p4 ⊕ p5 ⊕ p6 ⊕ p7 ⊕ p8 ⊕ p9 ⊕ p10 ⊕ p11 ⊕ p12 ⊕ p13 ⊕ p14 ⊕ p15 ⊕ p16 ⊕ p17 ⊕ p18 ⊕ p19 ⊕ p20 ⊕ p21 ⊕ p22 ⊕ p23) ⊕ d13
  f6 = refl

  g6 : ((p0 ⊕ p1 ⊕ p2 ⊕ p3 ⊕ p4 ⊕ p5 ⊕ p6 ⊕ p7 ⊕ p8 ⊕ p9 ⊕ p10 ⊕ p11 ⊕ p12 ⊕ p13 ⊕ p14 ⊕ p15 ⊕ p16 ⊕ p17 ⊕ p18 ⊕ p19 ⊕ p20 ⊕ p21 ⊕ p22 ⊕ p23) ⊕ d13) ⊕ z ≡ ((p0 ⊕ p1 ⊕ p2 ⊕ p3 ⊕ p4 ⊕ p5 ⊕ p6 ⊕ p7 ⊕ p8 ⊕ p9 ⊕ p10 ⊕ p11 ⊕ p12 ⊕ p13 ⊕ p14 ⊕ p15 ⊕ p16 ⊕ p17 ⊕ p18 ⊕ p19 ⊕ p20 ⊕ p21 ⊕ p22 ⊕ p23) ⊕ d13) ⊕ z
  g6 = cong (_⊕ z) f6

  f7 : (p0 ⊕ p1 ⊕ p2 ⊕ p3 ⊕ p4 ⊕ p5 ⊕ p6 ⊕ p7 ⊕ p8 ⊕ p9 ⊕ p10 ⊕ p11 ⊕ p12 ⊕ p13 ⊕ p14 ⊕ p15 ⊕ p16 ⊕ p17 ⊕ p18 ⊕ p19 ⊕ p20 ⊕ p21 ⊕ p22 ⊕ p23) ⊕ d12 ≡ (p0 ⊕ p1 ⊕ p2 ⊕ p3 ⊕ p4 ⊕ p5 ⊕ p6 ⊕ p7 ⊕ p8 ⊕ p9 ⊕ p10 ⊕ p11 ⊕ p12 ⊕ p13 ⊕ p14 ⊕ p15 ⊕ p16 ⊕ p17 ⊕ p18 ⊕ p19 ⊕ p20 ⊕ p21 ⊕ p22 ⊕ p23) ⊕ d12
  f7 = refl

  g7 : ((p0 ⊕ p1 ⊕ p2 ⊕ p3 ⊕ p4 ⊕ p5 ⊕ p6 ⊕ p7 ⊕ p8 ⊕ p9 ⊕ p10 ⊕ p11 ⊕ p12 ⊕ p13 ⊕ p14 ⊕ p15 ⊕ p16 ⊕ p17 ⊕ p18 ⊕ p19 ⊕ p20 ⊕ p21 ⊕ p22 ⊕ p23) ⊕ d12) ⊕ z ≡ ((p0 ⊕ p1 ⊕ p2 ⊕ p3 ⊕ p4 ⊕ p5 ⊕ p6 ⊕ p7 ⊕ p8 ⊕ p9 ⊕ p10 ⊕ p11 ⊕ p12 ⊕ p13 ⊕ p14 ⊕ p15 ⊕ p16 ⊕ p17 ⊕ p18 ⊕ p19 ⊕ p20 ⊕ p21 ⊕ p22 ⊕ p23) ⊕ d12) ⊕ z
  g7 = cong (_⊕ z) f7

  f8 : (p0 ⊕ p1 ⊕ p2 ⊕ p3 ⊕ p4 ⊕ p5 ⊕ p6 ⊕ p7 ⊕ p8 ⊕ p9 ⊕ p10 ⊕ p11 ⊕ p12 ⊕ p13 ⊕ p14 ⊕ p15 ⊕ p16 ⊕ p17 ⊕ p18 ⊕ p19 ⊕ p20 ⊕ p21 ⊕ p22 ⊕ p23) ⊕ d11 ≡ (p0 ⊕ p1 ⊕ p2 ⊕ p3 ⊕ p4 ⊕ p5 ⊕ p6 ⊕ p7 ⊕ p8 ⊕ p9 ⊕ p10 ⊕ p11 ⊕ p12 ⊕ p13 ⊕ p14 ⊕ p15 ⊕ p16 ⊕ p17 ⊕ p18 ⊕ p19 ⊕ p20 ⊕ p21 ⊕ p22 ⊕ p23) ⊕ d11
  f8 = refl

  g8 : ((p0 ⊕ p1 ⊕ p2 ⊕ p3 ⊕ p4 ⊕ p5 ⊕ p6 ⊕ p7 ⊕ p8 ⊕ p9 ⊕ p10 ⊕ p11 ⊕ p12 ⊕ p13 ⊕ p14 ⊕ p15 ⊕ p16 ⊕ p17 ⊕ p18 ⊕ p19 ⊕ p20 ⊕ p21 ⊕ p22 ⊕ p23) ⊕ d11) ⊕ z ≡ ((p0 ⊕ p1 ⊕ p2 ⊕ p3 ⊕ p4 ⊕ p5 ⊕ p6 ⊕ p7 ⊕ p8 ⊕ p9 ⊕ p10 ⊕ p11 ⊕ p12 ⊕ p13 ⊕ p14 ⊕ p15 ⊕ p16 ⊕ p17 ⊕ p18 ⊕ p19 ⊕ p20 ⊕ p21 ⊕ p22 ⊕ p23) ⊕ d11) ⊕ z
  g8 = cong (_⊕ z) f8

  f9 : (p0 ⊕ p1 ⊕ p2 ⊕ p3 ⊕ p4 ⊕ p5 ⊕ p6 ⊕ p7 ⊕ p8 ⊕ p9 ⊕ p10 ⊕ p11 ⊕ p12 ⊕ p13 ⊕ p14 ⊕ p15 ⊕ p16 ⊕ p17 ⊕ p18 ⊕ p19 ⊕ p20 ⊕ p21 ⊕ p22 ⊕ p23) ⊕ d13 ≡ (p0 ⊕ p1 ⊕ p2 ⊕ p3 ⊕ p4 ⊕ p5 ⊕ p6 ⊕ p7 ⊕ p8 ⊕ p9 ⊕ p10 ⊕ p11 ⊕ p12 ⊕ p13 ⊕ p14 ⊕ p15 ⊕ p16 ⊕ p17 ⊕ p18 ⊕ p19 ⊕ p20 ⊕ p21 ⊕ p22 ⊕ p23) ⊕ d13
  f9 = refl

  g9 : ((p0 ⊕ p1 ⊕ p2 ⊕ p3 ⊕ p4 ⊕ p5 ⊕ p6 ⊕ p7 ⊕ p8 ⊕ p9 ⊕ p10 ⊕ p11 ⊕ p12 ⊕ p13 ⊕ p14 ⊕ p15 ⊕ p16 ⊕ p17 ⊕ p18 ⊕ p19 ⊕ p20 ⊕ p21 ⊕ p22 ⊕ p23) ⊕ d13) ⊕ z ≡ ((p0 ⊕ p1 ⊕ p2 ⊕ p3 ⊕ p4 ⊕ p5 ⊕ p6 ⊕ p7 ⊕ p8 ⊕ p9 ⊕ p10 ⊕ p11 ⊕ p12 ⊕ p13 ⊕ p14 ⊕ p15 ⊕ p16 ⊕ p17 ⊕ p18 ⊕ p19 ⊕ p20 ⊕ p21 ⊕ p22 ⊕ p23) ⊕ d13) ⊕ z
  g9 = cong (_⊕ z) f9

  f10 : (p0 ⊕ p1 ⊕ p2 ⊕ p3 ⊕ p4 ⊕ p5 ⊕ p6 ⊕ p7 ⊕ p8 ⊕ p9 ⊕ p10 ⊕ p11 ⊕ p12 ⊕ p13 ⊕ p14 ⊕ p15 ⊕ p16 ⊕ p17 ⊕ p18 ⊕ p19 ⊕ p20 ⊕ p21 ⊕ p22 ⊕ p23) ⊕ d12 ≡ (p0 ⊕ p1 ⊕ p2 ⊕ p3 ⊕ p4 ⊕ p5 ⊕ p6 ⊕ p7 ⊕ p8 ⊕ p9 ⊕ p10 ⊕ p11 ⊕ p12 ⊕ p13 ⊕ p14 ⊕ p15 ⊕ p16 ⊕ p17 ⊕ p18 ⊕ p19 ⊕ p20 ⊕ p21 ⊕ p22 ⊕ p23) ⊕ d12
  f10 = refl

  g10 : ((p0 ⊕ p1 ⊕ p2 ⊕ p3 ⊕ p4 ⊕ p5 ⊕ p6 ⊕ p7 ⊕ p8 ⊕ p9 ⊕ p10 ⊕ p11 ⊕ p12 ⊕ p13 ⊕ p14 ⊕ p15 ⊕ p16 ⊕ p17 ⊕ p18 ⊕ p19 ⊕ p20 ⊕ p21 ⊕ p22 ⊕ p23) ⊕ d12) ⊕ z ≡ ((p0 ⊕ p1 ⊕ p2 ⊕ p3 ⊕ p4 ⊕ p5 ⊕ p6 ⊕ p7 ⊕ p8 ⊕ p9 ⊕ p10 ⊕ p11 ⊕ p12 ⊕ p13 ⊕ p14 ⊕ p15 ⊕ p16 ⊕ p17 ⊕ p18 ⊕ p19 ⊕ p20 ⊕ p21 ⊕ p22 ⊕ p23) ⊕ d12) ⊕ z
  g10 = cong (_⊕ z) f10

  f11 : (p0 ⊕ p1 ⊕ p2 ⊕ p3 ⊕ p4 ⊕ p5 ⊕ p6 ⊕ p7 ⊕ p8 ⊕ p9 ⊕ p10 ⊕ p11 ⊕ p12 ⊕ p13 ⊕ p14 ⊕ p15 ⊕ p16 ⊕ p17 ⊕ p18 ⊕ p19 ⊕ p20 ⊕ p21 ⊕ p22 ⊕ p23) ⊕ d11 ≡ (p0 ⊕ p1 ⊕ p2 ⊕ p3 ⊕ p4 ⊕ p5 ⊕ p6 ⊕ p7 ⊕ p8 ⊕ p9 ⊕ p10 ⊕ p11 ⊕ p12 ⊕ p13 ⊕ p14 ⊕ p15 ⊕ p16 ⊕ p17 ⊕ p18 ⊕ p19 ⊕ p20 ⊕ p21 ⊕ p22 ⊕ p23) ⊕ d11
  f11 = refl

  g11 : ((p0 ⊕ p1 ⊕ p2 ⊕ p3 ⊕ p4 ⊕ p5 ⊕ p6 ⊕ p7 ⊕ p8 ⊕ p9 ⊕ p10 ⊕ p11 ⊕ p12 ⊕ p13 ⊕ p14 ⊕ p15 ⊕ p16 ⊕ p17 ⊕ p18 ⊕ p19 ⊕ p20 ⊕ p21 ⊕ p22 ⊕ p23) ⊕ d11) ⊕ z ≡ ((p0 ⊕ p1 ⊕ p2 ⊕ p3 ⊕ p4 ⊕ p5 ⊕ p6 ⊕ p7 ⊕ p8 ⊕ p9 ⊕ p10 ⊕ p11 ⊕ p12 ⊕ p13 ⊕ p14 ⊕ p15 ⊕ p16 ⊕ p17 ⊕ p18 ⊕ p19 ⊕ p20 ⊕ p21 ⊕ p22 ⊕ p23) ⊕ d11) ⊕ z
  g11 = cong (_⊕ z) f11
