{-# OPTIONS --cubical --safe --guardedness #-}
module K8.Smoke where

import K8.FiniteVocabulary
import K8.GroundSets
import K8.FiniteSets
import K8.FiniteOperations
import K8.FiniteSubsets
import K8.FiniteUnion
import K8.FiniteAmbient
import K8.FinitePower
import K8.FiniteProduct
import K8.FiniteFibers
import K8.FiniteEnumeration
import K8.FiniteCountable
import K8.CountableUnion
import K8.MapVocabulary
import K8.PartialMaps
import K8.Presentation
import K8.MapOperations
import K8.Restriction
import K8.DomainFinite
import K8.RangeFinite
import K8.OmegaFinite
import K8.CoordinateDense
import K8.Cohen
import K8.CohenFibers
import K8.DistinctDense
import K8.Controls
import K8.RootCompatibility
import K8.SubsetOrder
import K8.CompletionOrder
import K8.FinitePairs
import K8.FinitePigeonhole
import K8.OmegaInduction
import K8.OmegaSuccessor
import K8.OmegaMax
import K8.OmegaPairing
import K8.LexOrder
import K8.DiagonalOrder
import K8.OmegaRecursion
import K8.RecursionInduction
import K8.DomainExtension
import K8.Uncountability
import K8.FamilyImages
import K8.CountableOperations
import K8.CountableZFC
import K8.CountableStars
import K8.DisjointFamilies
import K8.DeleteFamilies
import K8.LayerFamilies
import K8.DeltaSystem
import K8.ConnectedComponents
import K8.ComponentStep
import K8.CountableComponents
import K8.DomainFamilies
import K8.CCCTransfer
import K8.CodedCCCTransfer
import K8.CanonicalCertificate
import K8.ComponentRepresentatives
import K8.FullDeltaSystem
import K8.CohenCCC
import K8.CertifiedCCCTransfer
import K8.Theorem
