{-# OPTIONS --cubical --safe --guardedness #-}

-- [LJ-1.250] probe: THE D-10 AUDIT OF StepAgree / ApproxAgree.
--
-- The brief says: take ProbeLJ1249.agda and replace the two hypotheses
-- StepAgree / ApproxAgree with proofs.  This probe records WHY that is
-- impossible as stated, and names the term that would make it possible.
-- It runs no heavy cone; the decisive facts are reading-based and the
-- two controls (ProbeLJ1249.agda and the Condensation masters) are the
-- measurements, reported in lj-1.250-report.md.
--
-- FINDING 1 (D-10, C-45): the two hypotheses are UNCONSTRAINED.  In
-- ProbeLJ1249.agda the Body module takes
--     (ψs : Formula S 13) (ψa : Formula S 15)
--     (DefAt : ∀ {n} → Fin n → Fin n → Formula S n)
-- as parameters.  StepAgree is stated at ProbeLJ1249.agda:159-168:
--     ⟨ env ⊨ GB.S.stepBndAt ⟩ → ⟨ env ⊨ StepAt (2) (4) zero ⟩
-- GB.S.stepBndAt is built from ψs alone (ProbeLJ1249.agda:109-127);
-- StepAt is built from DefAt alone (GenSequence.agda:63-66).  NO
-- parameter, hypothesis or equation relates ψs to DefAt.  So the
-- statement is satisfiable-by-absurdity and unprovable at once: take
-- ψs satisfiable and DefAt the machine's (or any) step leaf that the
-- satisfiable ψs does not imply, and the implication is false.
-- This is the [LJ-1.244] φ₀ shape, one level up.  INFERRED by reading;
-- the same classification [LJ-1.246] gave its φ₀ refutation.
--
-- FINDING 2 (C-36): the concrete per-tower proof needs the leaf
-- adequacy LeafAgree (src/L/Condensation.lagda.md:7065), and that
-- module's telescope is OPEN.  LeafAgree takes
--     twelve-out / twelve-back   (src/L/Condensation.lagda.md:7097/7100)
-- which SatGraphAgree also takes (:6812/:6815).  The only thing that
-- could supply them is L.Condensation.TwelveAgree.AbstractFrame
-- instantiated at a real K, and its own comment says that is
-- "[LJ-1.113]'s 28 pieces of new content"
-- (src/L/Condensation/TwelveAgree.lagda.md:519-522), unbuilt at HEAD.
-- MEASURED: grep over src/ finds LeafAgree only at its definition
-- (three comment/definition lines) and no instantiation anywhere.
--
-- FINDING 3 (DD4): the structural lifting is generic and already
-- delivered.  extAtB→extAt sits at src/L/Condensation.lagda.md:2511,
-- and the ∃̇∈ → ∃̇ drop is ProbeDD25D5's LeafAgreeG.leaf-out
-- (agents/tasks/archive/LJ-1-34/ProbeDD25D5.agda:165-192).  Only the
-- leaf (DefBodyB ↔ DefBody) is per-tower, and its L-side form is the
-- open LeafAgree, not a closed theorem.
--
-- ONE agda process under GHCRTS="-A64m -I0 -M8g".  Never committed.

module LJ-1-250.ProbeLJ1250 where

-- This probe deliberately proves nothing: the two targets are
-- interfaces over unrelated leaves (finding 1), and the concrete term
-- is the open leaf supply (finding 2), named at file:line in the
-- report.  A compilable skeleton is the whole deliverable here.
