#!/usr/bin/env python3
"""LJ-1.185 probe generator: three spellings of ONE mathematical content.

THE QUESTION. `[LJ-1.155]:134-139` and `[LJ-1.145]:86-100` both compute the
seconds "billed outside every definition" by subtracting an `--profile=internal`
run from an `--profile=definitions` run. Agda 2.8.0 REFUSES to take both
accounts in one run, so the subtraction is the only method available. This
generator calibrates that subtraction.

THE THREE SPELLINGS, with identical mathematics in every one:

  base   the definitions at file level. NO module header, NO module
         application. If the `Definition` account covered every millisecond of
         `Typing`, this file's residue would be ZERO.
  tele   the same definitions inside ONE module with a telescope of `--width`
         hypotheses.
  apps   `tele`, plus `--apps` module applications of that module.

So `residue(base)` is the instrument's own floor, `residue(tele) - residue(base)`
prices the telescope, and `residue(apps) - residue(tele)` prices the
instantiation.

DD4. Nothing here names a tower, a stage or a formula. The carrier is a
private unary `N` declared in the file. The generator re-instantiates for the
J tower unchanged, because it never mentions either tower.

Usage:
    gen_probe.py --shape base|tele|apps --tag B --out <file.agda>
                 [--defs 12] [--ladder 13] [--width 24] [--apps 136]
"""
from __future__ import annotations

import argparse
import pathlib

HEAD = """-- LJ-1.185, probe {tag}: the {shape} spelling.
--
-- Generated by `agents/tasks/LJ-1-185/gen_probe.py`. Do not edit by hand.
-- shape={shape} defs={defs} ladder={ladder} width={width} apps={apps}
--
-- Read it TWICE, once with `--profile=definitions` and once with
-- `--profile=internal`. Agda 2.8.0 refuses both in one run.

{{-# OPTIONS --cubical --safe --guardedness #-}}

module LJ-1-185.ProbeLJ1185{tag} where

open import Cubical.Foundations.Prelude

-- A private unary carrier. It names nothing in either tower (DD4).

data N : Type where
  z : N
  s : N → N

infixl 6 _⊕_

_⊕_ : N → N → N
z     ⊕ m = m
(s n) ⊕ m = s (n ⊕ m)

-- A doubling ladder, so one name stands for a deep term.
"""


def ladder(k: int) -> str:
    out = ["\nd0 : N\nd0 = s z\n"]
    for i in range(1, k + 1):
        out.append(f"\nd{i} : N\nd{i} = d{i - 1} ⊕ d{i - 1}\n")
    return "".join(out)


def bodies_free(n: int, k: int) -> str:
    """`n` definition pairs at file level.

    Each pair is one REAL conversion, which normalizes a deep unary term, and
    one meta solve through `cong`, which occurs-checks against it. This is the
    calibration file: it holds no module header and no module application, so
    its residue is the instrument's own floor.
    """
    out = []
    for i in range(n):
        lvl = k - (i % 3)
        out.append(
            f"\nf{i} : d{lvl} ⊕ z ≡ d{lvl}\n"
            f"f{i} = refl\n"
            f"\ng{i} : (d{lvl} ⊕ z) ⊕ z ≡ d{lvl} ⊕ z\n"
            f"g{i} = cong (_⊕ z) f{i}\n"
        )
    return "".join(out)


def bodies_param(n: int, k: int, width: int) -> str:
    """`n` definition pairs under a telescope, with the parameters IN the type.

    The bodies are `refl` on syntactically identical sides, so CHECKING them is
    free. What is not free is COPYING them: a module application substitutes
    every argument into every one of these types. So the `tele` against `apps`
    pair isolates instantiation and nothing else.
    """
    ps = " ⊕ ".join(f"p{j}" for j in range(width))
    out = []
    for i in range(n):
        lvl = k - (i % 3)
        t = f"({ps}) ⊕ d{lvl}"
        out.append(
            f"\n  f{i} : {t} ≡ {t}\n"
            f"  f{i} = refl\n"
            f"\n  g{i} : ({t}) ⊕ z ≡ ({t}) ⊕ z\n"
            f"  g{i} = cong (_⊕ z) f{i}\n"
        )
    return "".join(out)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--shape", required=True, choices=("base", "tele", "apps"))
    ap.add_argument("--tag", required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--defs", type=int, default=12)
    ap.add_argument("--ladder", type=int, default=13)
    ap.add_argument("--width", type=int, default=24)
    ap.add_argument("--apps", type=int, default=136)
    a = ap.parse_args()

    text = HEAD.format(
        tag=a.tag, shape=a.shape, defs=a.defs, ladder=a.ladder,
        width=a.width, apps=a.apps if a.shape == "apps" else 0,
    )
    text += ladder(a.ladder)

    if a.shape == "base":
        text += "\n-- The definitions, at file level.\n"
        text += bodies_free(a.defs, a.ladder)
    else:
        ps = " ".join(f"p{i}" for i in range(a.width))
        text += f"\n-- The definitions, under a telescope of {a.width} hypotheses.\n"
        text += f"\nmodule Body ({ps} : N) where\n"
        text += bodies_param(a.defs, a.ladder, a.width)
        if a.shape == "apps":
            args = " ".join(["d0"] * a.width)
            text += f"\n-- {a.apps} module applications of `Body`.\n\n"
            for j in range(a.apps):
                text += f"module App{j} = Body {args}\n"

    pathlib.Path(a.out).write_text(text, encoding="utf-8")
    print(f"wrote {a.out}: shape={a.shape} defs={a.defs} ladder={a.ladder} "
          f"width={a.width} apps={a.apps if a.shape == 'apps' else 0}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
