{-# OPTIONS --cubical --safe --guardedness #-}

-- K5 Track H, seam 2: the two activity bullets are FREE at Uof G.
--
-- K5/RoundTrip.agda states its theorem over a bare subset U of the algebra
-- with two entailments in the telescope:
--
--     U-to-below   : b in U implies some condition below b has its image in U
--     U-from-below : a condition below b with its image in U puts b in U
--
-- Architecture section 6.3 claims these hold at U := Uof G by ⊆ˢ-transitivity
-- alone, with no order reflection, no excluded middle, no `recover` and no
-- density of the image, and that the earlier reading which charged the round
-- trip K2's recover (TranslateForward.agda:30-31) mispriced it. This file is
-- the check. Both are one PT.map. Neither takes LEM ℓ, neither takes a filter
-- law, neither takes genericity, and neither names a coded dense set.
--
-- THE MEASURED SHAPE OF THE INTERFACE, and it is not Track E's. Track E states
-- its valuation agreement over an ARBITRARY U with the bridge at images,
-- p ∈ G ⟺ U (i p) (K5/Agreement.agda:262-264), and says so deliberately. That
-- bridge does NOT give U-to-below: a subset of the algebra can reflect G at
-- the image of the embedding and still contain an element with no condition
-- below it that G sees. U-to-below says U is GENERATED by the images of
-- members of G, which is Uof's definition (K5/Generic.agda:150-151) and not a
-- consequence of reflection. So the round trip is a theorem about the
-- pushforward and not about any U corresponding to G, and that is the precise
-- form of architecture 6.3's closing sentence that the coincidence is NOT free
-- at an arbitrary ultrafilter.
--
-- The value surface stays abstract here; K5/RoundTripAtValue.agda is the seam
-- that fills it from K3's Valuation. Splitting the two keeps each file at one
-- supplier.

open import Base.Prelude
open import Base.Truth
open import FOL.ZFStructure using ( ZFStructure )
import OrdinaryProfile
import K4.Algebra
import K5.Frame
import K5.Generic
import K5.RoundTrip

module K5.RoundTripAtUof {ℓ} (𝒮 : ZFStructure (hPropAlgebra ℓ)) where

open import FOL.ZFStructure using ( module hPropStructure )
open import Cubical.Induction.WellFounded using ( WellFounded )
import Cubical.HITs.PropositionalTruncation as PT

open TruthAlgebra (hPropAlgebra ℓ)
open hPropStructure 𝒮

open K4.Algebra 𝒮 using ( Pt; ⊆ˢ-trans; Lattice; Complement; CodedComplete )

module Poset (carrier order : S) where

  open K5.Frame.Poset 𝒮 carrier order using ( Cond; ForcingBase )

  module Image
    (ext   : OrdinaryProfile.Extensionality 𝒮)
    (paths : (x y : S) → (x ≈ˢ y) ≡ ((x ≡ y) , isSetS x y))
    (B : S) (L : Lattice B) (Cm : Complement B L) (Kc : CodedComplete B L)
    (fb : ForcingBase B L Cm)
    where

    -- The three opens are ProbeD's (K5/ProbeD.agda:55-59) minus
    -- K4.Implication, which nothing here names. None of the three re-exports
    -- what another supplies, so no name is ambiguous.

    open ForcingBase fb
    open K5.Frame.Poset.Forcing 𝒮 carrier order ext paths B L Cm Kc fb
    open K5.Generic.Poset.Image 𝒮 carrier order ext paths B L Cm Kc fb

--------------------------------------------------------------------------------
-- The two bullets of architecture 6.3
--------------------------------------------------------------------------------

    module At (G : FS.Sub) where

      open K5.Generic.Poset.Image.Laws
             𝒮 carrier order ext paths B L Cm Kc fb G
        using ( generic-forward )

      -- FIRST BULLET. If b is in Uof G then some member p of G forces b, so p
      -- lies in the coded extension of b by ⊩ᴮ-mem (K5/Frame.agda:291-292),
      -- and the image of p is in Uof G by generic-forward
      -- (K5/Generic.agda:169-170), witnessed by p itself and not by a meet.
      --
      -- FREE. No LEM, no filter law, no genericity, no separativity, no coded
      -- dense set. It is one PT.map over the join Uof is defined as.

      U-to-below : (b : Pt B) → ⟨ Uof G b ⟩
                 → ⟨ ⋁ Cond (λ q → (fst q ∈ˢ below b) ⊓ Uof G (i q)) ⟩
      U-to-below b =
        PT.map (λ { (p , hp , hf) → p , ⊩ᴮ-mem p b hf , generic-forward p hp })

      -- SECOND BULLET. If the condition q lies in the coded extension of b
      -- then i q ≤ᴮ b by below-out (K5/Frame.agda:201), and if some member r
      -- of G forces i q then i r ≤ᴮ i q, so i r ≤ᴮ b by ⊆ˢ-transitivity and r
      -- witnesses b in Uof G.
      --
      -- FREE, and this is the direction architecture 6.3 says was mispriced.
      -- The chain is ⊆ˢ-trans and the two transports along the seal of _⊩ᴮ_,
      -- and nothing else appears in it: no order reflection (T-A1, refuted at
      -- InstancesCompletion.agda:131-134), no injectivity of i (there is none
      -- and never will be, TranslateForward.agda:33-36), no `recover`
      -- (Certificate.agda:434-435, uninhabited anywhere in the programme), and
      -- no density of the image (ForcingBase.i-dense is not projected here).

      U-from-below : (b : Pt B) (q : Cond) → ⟨ fst q ∈ˢ below b ⟩
                   → ⟨ Uof G (i q) ⟩ → ⟨ Uof G b ⟩
      U-from-below b q hqb =
        PT.map (λ { (r , hr , hf) →
                    r , hr , ⊩ᴮ-intro r b
                               (⊆ˢ-trans (⊩ᴮ-elim r (i q) hf)
                                         (below-out b q hqb)) })

--------------------------------------------------------------------------------
-- The theorem, at Uof G
--------------------------------------------------------------------------------

      -- The kernel, the translations and the value surface stay flat, exactly
      -- as in K5/RoundTrip.agda; what this module supplies is U and its two
      -- entailments. Applying the round trip here is what turns the two
      -- bullets above into ext-onto-raw at the CORRESPONDING filter, which is
      -- the only subset of the algebra K5 ever names.

      module Round
        (entry       : S → S → S)
        (entry-inj   : {x b y c : S} → entry x b ≡ entry y c
                     → (x ≡ y) × (b ≡ c))
        (Child       : S → S → Type ℓ)
        (child-entry : (x b n : S) → ⟨ entry x b ∈ˢ n ⟩ → Child x n)
        (child-wf    : WellFounded Child)
        (trᴮ : S → S)
        (trᴮ-entries : (n e : S) → (e ∈ˢ trᴮ n)
                     ≡ ⋁ S (λ x → ⋁ S (λ p → ⋁ ⟨ p ∈ˢ carrier ⟩ (λ hp →
                         (entry x p ∈ˢ n)
                         ⊓ (e ≈ˢ entry (trᴮ x) (fst (i (p , hp))))))))
        (trᴾ : S → S)
        (trᴾ-entries : (n e : S) → (e ∈ˢ trᴾ n)
                     ≡ ⋁ S (λ x → ⋁ S (λ b → ⋁ ⟨ b ∈ˢ B ⟩ (λ hb → ⋁ S (λ p →
                         (entry x b ∈ˢ n) ⊓ ((p ∈ˢ below (b , hb))
                            ⊓ (e ≈ˢ entry (trᴾ x) p)))))))
        (_≈[U]_   : S → S → Ω)
        (‖Active‖ : S → S → Ω)
        (≈-intro  : {m n : S}
                  → ((x : S) → ⟨ ‖Active‖ x m ⟩
                     → ⟨ ⋁ S (λ y → ‖Active‖ y n ⊓ (x ≈[U] y)) ⟩)
                  → ((y : S) → ⟨ ‖Active‖ y n ⟩
                     → ⟨ ⋁ S (λ x → ‖Active‖ x m ⊓ (x ≈[U] y)) ⟩)
                  → ⟨ m ≈[U] n ⟩)
        (active-in  : (x n b : S) (hb : ⟨ b ∈ˢ B ⟩)
                    → ⟨ entry x b ∈ˢ n ⟩ → ⟨ Uof G (b , hb) ⟩
                    → ⟨ ‖Active‖ x n ⟩)
        (active-out : (x n : S) (Q : Ω) → ⟨ ‖Active‖ x n ⟩
                    → ((b : S) (hb : ⟨ b ∈ˢ B ⟩) → ⟨ entry x b ∈ˢ n ⟩
                       → ⟨ Uof G (b , hb) ⟩ → ⟨ Q ⟩)
                    → ⟨ Q ⟩)
        where

        open K5.RoundTrip.Kernel.Translation.Value 𝒮
               entry entry-inj Child child-entry child-wf paths
               carrier B (λ q → fst (i q)) (λ q → snd (i q)) below
               trᴮ trᴮ-entries trᴾ trᴾ-entries
               (Uof G) _≈[U]_ ‖Active‖ ≈-intro active-in active-out
               U-to-below U-from-below
          public using ( ext-onto-raw )
